workspace(name = "info_chys_cbu")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "com_google_googletest",
  url = "https://github.com/google/googletest/archive/release-1.11.0.tar.gz",
  sha256 = "b4870bf121ff7795ba20d20bcdd8627b8e088f2d1dab299a031c1034eddc93d5",
  strip_prefix = "googletest-release-1.11.0",
)
